export type Language = 'de' | 'en';

export const translations = {
  de: {
    nav: { home: 'Startseite', story: 'Unsere Geschichte', gallery: 'Galerie', events: 'Vergangene Events', impressum: 'Impressum', request: 'Event anfragen' },
    hero: { since: 'Seit 2026', title: 'La Favola', subtitle: 'Pizza Napoletana & Catering', description: 'Handgemacht, traditionsbewusst und mit viel Liebe im Feuer gebacken.', request: 'Event anfragen', story: 'Unsere Geschichte', scroll: 'Nach unten scrollen' },
    story: { eyebrow: 'Unsere Geschichte', title: 'Eine Leidenschaft,<br />die man schmeckt', paragraphs: ['La Favola steht für echte neapolitanische Pizza und die besonderen Geschichten, die an einem Tisch entstehen.', 'Unser Teig ruht mindestens 24 Stunden. Beste Zutaten, viel Zeit und ein heißer Ofen sorgen für den charakteristischen Rand und den unverwechselbaren Geschmack.', 'Ob Hochzeit, Geburtstag, Firmenevent oder Workshop: Wir bringen ein Stück Neapel direkt zu Ihnen.'], oven: 'Im Ofen', rest: 'Teigruhe', heat: 'Ofenhitze' },
    services: { eyebrow: 'Unsere Leistungen', title: 'Pizza für besondere Momente', description: 'Wir machen Ihr Event zu einem Fest: persönlich, frisch und mit echter neapolitanischer Handwerkskunst.', request: 'Jetzt anfragen' },
    ingredients: { eyebrow: 'Unsere Zutaten', title: 'Das Beste beginnt bei den Zutaten', description: 'Ehrliche Zutaten, sorgfältig ausgewählt und mit Respekt vor dem Handwerk verarbeitet.' },
    gallery: { eyebrow: 'Bildergalerie', title: 'Momente von La Favola', description: 'Einblicke in unsere Pizza, unser Handwerk und die Events von La Favola.', request: 'Jetzt anfragen', empty: 'Sobald Bilder im Galerieordner liegen, werden sie hier alphabetisch angezeigt.' },
    request: { eyebrow: 'Event anfragen', title: 'Ihr Event. Unsere Pizza.', description: 'La Favola ist ausschließlich für Events und Catering da. Senden Sie uns Ihre Anfrage – wir melden uns persönlich bei Ihnen.', firstName: 'Vorname', lastName: 'Nachname', email: 'E-Mail-Adresse', people: 'Personenanzahl', event: 'Event', customEvent: 'Eigenes Event', customPlaceholder: 'Art des Events', message: 'Ihre Anfrage', messagePlaceholder: 'Erzählen Sie uns von Ihrem Event, dem Datum und Ihren Wünschen …', submit: 'Anfrage senden', required: 'Bitte füllen Sie alle Pflichtfelder aus.', sending: 'Wird gesendet …', successTitle: 'Vielen Dank für Ihre Anfrage!', successText: 'Wir haben Ihnen eine Bestätigung per E-Mail gesendet und melden uns persönlich bei Ihnen.', error: 'Die Anfrage konnte gerade nicht gesendet werden. Bitte versuchen Sie es später erneut.', captcha: 'Bitte bestätigen Sie, dass Sie kein Roboter sind.', mailNote: 'Sie erhalten eine Bestätigung an Ihre E-Mail-Adresse.' },
    events: { eyebrow: 'Vergangene Events', title: 'Abende, die bleiben', description: 'Ein Rückblick auf unsere gemeinsamen Genussmomente, Tastings und Feiern.', gallery: 'Galerie ansehen' },
    impressum: { eyebrow: 'Impressum', title: 'Kontakt & Besuch', find: 'So finden Sie uns', address: 'Adresse', phone: 'Telefon', email: 'E-Mail', hours: 'Öffnungszeiten', closed: 'Geschlossen', legal: 'Rechtliche Informationen', company: 'Unternehmen', director: 'Geschäftsführung', register: 'Handelsregister', responsible: 'Verantwortlich für den Inhalt', authority: 'Aufsichtsbehörde', dispute: 'Streitbeilegung' },
    captcha: { title: 'Sicherheitsprüfung', description: 'Lösen Sie die kleine Rechenaufgabe, um fortzufahren.', answer: 'Ihre Antwort', verify: 'Bestätigen', invalid: 'Die Antwort ist leider nicht korrekt.', close: 'Schließen', initial: 'Zum Schutz vor automatisierten Zugriffen ist eine kurze Prüfung erforderlich.', impressum: 'Bitte bestätigen Sie kurz, dass Sie kein Roboter sind, bevor Sie das Impressum öffnen.' },
    footer: { story: 'Geschichte', gallery: 'Galerie', events: 'Events', crafted: 'Mit Leidenschaft in Deutschland gebacken.', rights: 'Alle Rechte vorbehalten.', social: 'Social Media' },
  },
  en: {
    nav: { home: 'Home', story: 'Our Story', gallery: 'Gallery', events: 'Previous Events', impressum: 'Impressum', request: 'Request an event' },
    hero: { since: 'Since 2026', title: 'La Favola', subtitle: 'Pizza Napoletana & Catering', description: 'Handmade, rooted in tradition, and baked with care in a blazing oven.', request: 'Request an event', story: 'Our Story', scroll: 'Scroll down' },
    story: { eyebrow: 'Our Story', title: 'A passion<br />you can taste', paragraphs: ['La Favola is about authentic Neapolitan pizza and the special stories that happen around a table.', 'Our dough rests for at least 24 hours. The finest ingredients, time, and a blazing oven create its signature crust and unmistakable flavor.', 'Whether it is a wedding, birthday, corporate event, or workshop, we bring a little piece of Naples to you.'], oven: 'In the oven', rest: 'Dough rest', heat: 'Oven heat' },
    services: { eyebrow: 'Our Services', title: 'Pizza for special moments', description: 'We turn your event into a celebration: personal, fresh, and made with true Neapolitan craft.', request: 'Request now' },
    ingredients: { eyebrow: 'Our Ingredients', title: 'The best starts with ingredients', description: 'Honest ingredients, carefully selected and handled with respect for the craft.' },
    gallery: { eyebrow: 'Photo Gallery', title: 'Moments at La Favola', description: 'A glimpse into our pizza, our craft, and the events of La Favola.', request: 'Request now', empty: 'Images added to the gallery folder will appear here in alphabetical order.' },
    request: { eyebrow: 'Request an event', title: 'Your event. Our pizza.', description: 'La Favola is exclusively available for events and catering. Send us your request and we will get back to you personally.', firstName: 'First name', lastName: 'Last name', email: 'Email address', people: 'Number of guests', event: 'Event', customEvent: 'Custom event', customPlaceholder: 'Type of event', message: 'Your request', messagePlaceholder: 'Tell us about your event, date, and wishes …', submit: 'Send request', required: 'Please complete all required fields.', sending: 'Sending …', successTitle: 'Thank you for your request!', successText: 'We sent a confirmation email and will get back to you personally.', error: 'The request could not be sent right now. Please try again later.', captcha: 'Please confirm that you are not a robot.', mailNote: 'You will receive a confirmation at your email address.' },
    events: { eyebrow: 'Previous Events', title: 'Evenings to remember', description: 'A look back at the gatherings, tastings, and celebrations we shared together.', gallery: 'View gallery' },
    impressum: { eyebrow: 'Impressum', title: 'Visit & Contact', find: 'Find Us', address: 'Address', phone: 'Phone', email: 'Email', hours: 'Opening Hours', closed: 'Closed', legal: 'Legal Information', company: 'Company', director: 'Managing Director', register: 'Commercial Register', responsible: 'Responsible for content', authority: 'Supervisory authority', dispute: 'Dispute resolution' },
    captcha: { title: 'Security check', description: 'Solve the small calculation to continue.', answer: 'Your answer', verify: 'Verify', invalid: 'That answer is not correct.', close: 'Close', initial: 'A short check is required to protect the site from automated access.', impressum: 'Please confirm that you are not a robot before opening the legal information.' },
    footer: { story: 'Story', gallery: 'Gallery', events: 'Events', crafted: 'Made with passion in Germany.', rights: 'All rights reserved.', social: 'Social media' },
  },
} as const;

export type Copy = (typeof translations)[Language];
